name: Deploy to GCP Cloud Functions

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider2
        service_account: 817261716888-compute@developer.gserviceaccount.com

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy db2KeepAlive \
          --entry-point=db2_keep_alive \
          --runtime=python311 \
          --trigger-http \
          --allow-unauthenticated \
          --project=sigma-outcome \
          --region=us-central1
