name: Deploy to GCP Cloud Functions (2nd Gen)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Functions
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider2'
          service_account: '817261716888-compute@developer.gserviceaccount.com'

      - name: Deploy to Cloud Functions (Gen2)
        run: |
          gcloud functions deploy db2-keep-alive \
            --gen2 \
            --region=us-central1 \
            --runtime=python311 \
            --entry-point=app \
            --source=. \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars="DB2_PASSWORD=${{ secrets.DB2_PASSWORD }}"
