name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider2'
          service_account: '817261716888-compute@developer.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Build Docker image and submit to GCR
        run: |
          gcloud builds submit \
            --tag gcr.io/sigma-outcome/db2-keep-alive \
            --project=sigma-outcome

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy db2-keep-alive \
            --image gcr.io/sigma-outcome/db2-keep-alive \
            --region=us-central1 \
            --project=sigma-outcome \
            --allow-unauthenticated \
            --port=8080 \
            --memory=512Mi \
            --set-env-vars="DB2_PASSWORD=${{ secrets.DB2_PASSWORD }}"
