name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider2'
          service_account: '817261716888-compute@developer.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/sigma-outcome/db2-keep-alive

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy db2-keep-alive \
            --image gcr.io/sigma-outcome/db2-keep-alive \
            --region us-central1 \
            --platform managed \
            --project sigma-outcome \
            --memory 512Mi \
            --port 8080 \
            --allow-unauthenticated \
            --set-env-vars DB2_PASSWORD=${{ secrets.DB2_PASSWORD }}
