name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider2'
          service_account: '817261716888-compute@developer.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy db2-keep-alive \
            --gen2 \
            --runtime=python39 \
            --region=us-central1 \
            --project=sigma-outcome \
            --source=. \
            --entry-point=db2_keep_alive \
            --trigger-http \
            --no-allow-unauthenticated \ # <--- 修改在这里
            --set-env-vars="DB2_PASSWORD=${{ secrets.DB2_PASSWORD }},GCP_REGION=us-central1,ENV_MODE=practice,GIT_COMMIT_SHA=${{ github.sha }}"