name: Deploy to GCP Cloud Functions

on:
  push:
    branches: [main]  # 或你实际使用的分支

permissions:
  contents: read
  id-token: write  # 必须打开，用于 OIDC 身份验证

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: 817261716888-compute@developer.gserviceaccount.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy db2KeepAlive \
            --runtime python311 \
            --trigger-http \
            --allow-unauthenticated \
            --entry-point main \
            --project sigma-outcome \
            --region us-central1 \
            --source .
