name: Deploy Python Cloud Function to GCP

on:
  push:
    branches:
      - main  # 或者你的主分支名称，比如 master

jobs:
  deploy:
    name: Deploy to GCP Cloud Functions
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # 需要这个权限来获取 OIDC token 给 Workload Identity Federation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: '817261716888-compute@developer.gserviceaccount.com'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # 与你的云函数运行时匹配

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy db2-keep-alive \
          --project=sigma-outcome \
          --region=us-central1 \
          --runtime=python312 \
          --source=. \
          --entry-point=db2_keep_alive_python \
          --trigger-http \
          --service-account=817261716888-compute@developer.gserviceaccount.com
          # 注意：这里没有 --allow-unauthenticated，因为我们要的是私有函数