name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy to Cloud Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/817261716888/locations/global/workloadIdentityPools/github-pool/providers/github-provider2"
          service_account: "817261716888-compute@developer.gserviceaccount.com"

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Functions (Gen2)
        run: |
          gcloud functions deploy db2-keep-alive \
            --project=sigma-outcome \
            --gen2 \
            --region=us-central1 \
            --runtime=python311 \
            --entry-point=app \
            --source=. \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars="DB2_PASSWORD=${{ secrets.DB2_PASSWORD }}"
